# Generated by Django 5.2.4 on 2026-08-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('whatsapp', 'וואטסאפ')], default='whatsapp', max_length=20, verbose_name='סוג')),
                ('page', models.CharField(max_length=120, verbose_name='עמוד')),
                ('campaign', models.CharField(blank=True, max_length=80, verbose_name='קמפיין')),
                ('utm_source', models.CharField(blank=True, max_length=80, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=80, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=80, verbose_name='utm_campaign')),
                ('referrer', models.CharField(blank=True, max_length=120, verbose_name='מפנה (דומיין)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='בתאריך')),
            ],
            options={
                'verbose_name': 'קליק',
                'verbose_name_plural': 'קליקים',
                'ordering': ['-created_at'],
            },
        ),
    ]
