# Generated by Django 5.2.4 on 2026-08-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(blank=True, max_length=120, verbose_name='עסק'),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, verbose_name='הערות'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('site', 'אתר'), ('whatsapp', 'וואטסאפ'), ('warm', 'היכרות'), ('cold-email', 'מייל קר'), ('linkedin', 'לינקדאין'), ('referral', 'הפניה'), ('other', 'אחר')], default='site', max_length=20, verbose_name='מקור'),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'חדש'), ('contacted', 'יצרתי קשר'), ('audit-sent', 'נשלח אבחון'), ('plan-sent', 'נשלחה הצעה'), ('migrating', 'בהעברה'), ('won', 'נסגר'), ('lost', 'אבד')], default='new', max_length=20, verbose_name='שלב'),
        ),
    ]
